version: 2

builds:
  - id: kafkaspectre
    binary: kafkaspectre
    main: ./cmd/kafkaspectre
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.GitCommit={{.Commit}} -X main.BuildDate={{.Date}}

archives:
  - id: default
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: ppiankov
    name: kafkaspectre
  prerelease: auto
  name_template: "Release {{ .Tag }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

brews:
  -
    name: "kafkaspectre"
    homepage: "https://github.com/ppiankov/kafkaspectre"
    description: "Kafka cluster auditor — identifies unused, orphaned, and misconfigured topics"
    license: "MIT"
    repository:
      owner: ppiankov
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "kafkaspectre"
    test: |
      assert_match "kafkaspectre", shell_output("#{bin}/kafkaspectre version")
